services:
  visualizer:
    image: ghcr.io/blockscout/visualizer:${VISUALIZER_DOCKER_TAG:-latest}
    platform: linux/amd64
    container_name: 'visualizer'
    env_file:
      -  ../envs/common-visualizer.env
